version: '3.9'

services:
  db:
    ports:
      - 5432:5432
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mines
      POSTGRES_PASSWORD: mines
      POSTGRES_DB: mines
